name: coral_reef
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.1
  firebase_analytics: ^7.1.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  firebase_messaging: ^9.0.0
  firebase_database: ^6.1.0
  firebase_storage: ^8.0.4
  firebase_dynamic_links: ^2.0.1
  sign_in_with_apple: ^3.0.0
  google_sign_in: ^5.0.0
  flutter_login_facebook: ^1.0.0
  flutter_svg: ^0.19.3
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  flutter_secure_storage: ^4.1.0
  fluttertoast: ^7.1.8
  rxdart: ^0.26.0
  vertical_weight_slider: ^1.0.0
  flutter_xlider: ^3.4.0
  syncfusion_flutter_datepicker: ^19.1.58-beta
  syncfusion_flutter_gauges: ^19.1.58
  date_picker_timeline: ^1.2.3
  flutter_linear_datepicker: ^1.1.2
  sleek_circular_slider: ^2.0.0
  shimmer: ^1.1.2
  truncate: ^3.0.1
  readmore: ^2.0.0
  file_picker: ^3.0.1
  flutter_image_compress: ^1.0.0
  video_compress: ^3.0.0
  image_cropper: ^1.4.0
  device_info: ^2.0.0
  sn_progress_dialog: ^1.0.1
  sqflite: ^1.3.0
  step_progress_indicator: ^0.2.5+8
  progress_bars: ^0.0.3
  extended_image: ^3.0.0-non-null-safety
  chewie: ^1.0.0
  video_player: ^2.1.1
  giphy_picker: ^2.0.0
  apple_sign_in: ^0.1.0
  syncfusion_flutter_barcodes: ^19.1.58
  fl_chart:
  akvelon_flutter_share_plugin: ^1.0.4
  clipboard: ^0.1.3
  swipe_refresh: ^1.0.0
#  flutter_qrcode_scanner: ^0.0.7
#  flutter_plugin_qr_scanner: ^0.0.1
  flutter_local_notifications: ^5.0.0+3
  uuid: ^3.0.4
  provider: ^5.0.0
  url_launcher: ^6.0.3
  permission_handler: ^7.1.0
  datetime_picker_formfield: ^2.0.0
  syncfusion_flutter_maps: ^19.1.58-beta
  shot_widget: ^1.0.0
  direct_select: ^1.0.3
  flutter_switch: ^0.3.1
  toggle_switch: ^0.1.9
  google_maps_flutter: ^2.0.3
  geolocator:
  flutter_polyline_points: ^1.0.0
  percent_indicator: ^3.0.1
  pedometer: ^3.0.0
  stacked: ^2.1.5
  get_it: ^6.0.0
  flutter_countdown_timer: ^4.1.0
  flutter_background_service: ^0.1.4
  location: ^4.1.1
  screen: ^0.0.5
  group_button: ^2.2.2
  jiffy: ^4.1.0
  time_range_picker: ^2.0.1
#  carp_core: ^0.20.0
#  carp_mobile_sensing: ^0.20.0
#  carp_audio_package: ^0.20.0
#  share_files_and_screenshot_widgets: ^1.0.3
#  hexcolor: ^2.0.3



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/gifs/
    - assets/images/
    - assets/icons/
    - assets/symptoms/
    - assets/well_being/
    - assets/diet/
    - assets/exercise/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AvenirNextBold
      fonts:
        - asset: assets/fonts/avenir_next/AvenirNext-Bold.ttf
    - family: AvenirNextDemiBold
      fonts:
        - asset: assets/fonts/avenir_next/AvenirNext-DemiBold.ttf
    - family: AvenirNextMedium
      fonts:
        - asset: assets/fonts/avenir_next/AvenirNext-Medium.ttf
    - family: AvenirNextRegular
      fonts:
        - asset: assets/fonts/avenir_next/AvenirNext-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
