import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:coral_reef/ListItem/model_baby_body_info.dart';
import 'package:coral_reef/ListItem/model_tips.dart';

import '../../../constants.dart';

class PregnancyServices {

  PregnancyServices();

  Future<Map<String, dynamic>> getSymptomsByDate(String week) async {

    Map<String, dynamic> syms = new Map();

    List<dynamic> msd = [];

    // String _date = "${today.year}-${today.month}-${today.day}";
    DocumentSnapshot query = await FirebaseFirestore.instance.collection("users").doc(user.uid).collection("pregnancy-symptoms").doc("week-$week").get();

    if(query.exists) {
      Map<String, dynamic> data = query.data();
      List<dynamic> m = data["moods"];
      List<dynamic> s = data["symptoms"];
      List<dynamic> d = data["discharge"];
      String note = data["note"];

      msd.addAll(m);
      msd.addAll(s);
      msd.addAll(d);

      syms["msd"] = msd;
      syms["note"] = note;
    }

    return syms;
  }

  Future<List<PregnancyTips>> getTips() async {

    List<PregnancyTips> tips = [];

    QuerySnapshot query = await FirebaseFirestore.instance.collection("db").doc("tips").collection("pregnancy").orderBy("timestamp", descending: true).get();

    if(query.size > 0) {

      query.docs.forEach((tip) {
        PregnancyTips pregnancyTips = PregnancyTips.fromSnapshot(tip.data());
        tips.add(pregnancyTips);
      });
    }

    return tips;
  }

  List<PregnancyBBInfo> getPregnancyInfoData() {
    return [
      PregnancyBBInfo(week: 1, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_1.mp4?alt=media&token=ee4a6d6d-596f-41a1-90ef-4ca644a97561", babyText: "", bodyText: ""),
      PregnancyBBInfo(week: 2, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_2.mp4?alt=media&token=c97cc8d1-3010-42c9-826c-016bab35a753", babyText: "", bodyText: ""),
      PregnancyBBInfo(week: 3, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_3.mp4?alt=media&token=585cc98c-acd4-4ceb-aa33-004852f66a0b", babyText: "", bodyText: ""),
      PregnancyBBInfo(week: 4, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_4.mp4?alt=media&token=07e62369-12a0-4225-ab3e-7e4a10c9d024", babyText: "At 4 weeks into pregnancy, the fertilized egg enters the uterus where the embryo (your baby) will develop. Here the amniotic sac filled with amniotic fluid will surround and protect your baby as he or she grows. Attached to it will be the yolk sac, which will nourish the embryo in these early weeks.", bodyText: "As the embryo is implanted within the endometrium you may experience mild cramping and even spotting may occur. Breast may be feeling tender, a bit of fatigue maybe nausea, these can easily be mistaken for the onset of your period, since this happens around that time of the month. The implanted embryo triggers a hormone called human chorionic gonadotropin (HCG) that helps to maintain the uterus lining and signals the ovary to stop releasing eggs each month. No more monthly periods ☺ Taking a pregnancy test now you will definitely see a double line! See your doctor to ensure that you are doing what is best for you and the bundle of joy inside your tummy."),
      PregnancyBBInfo(week: 5, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_5.mp4?alt=media&token=57d83c01-2e27-42cf-8c84-e16d3d881c52", babyText: "At week 5 the embryo starts to take shape, more like a tadpole at this point. The neural tube is where the brain, spinal cord and nerves will develop. Within this layer of tube is where the muscles, skeleton, heart and circulatory system will develop. Also, at this stage lungs and the urinary system will start to develop. You’d be surprised to know that small buds on both sides of the body will start to grow into arms and legs.", bodyText: "As your baby grows and you are 100% positive you are pregnant, you may be feeling pregnancy symptoms, like nausea (morning sickness), the frequent urge to pee and your breasts may be tender. As your doctor would have advised, taking folic acid at this stage is essential to the proper development of the baby to prevent any defects at this crucial stage."),
      PregnancyBBInfo(week: 6, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_6.mp4?alt=media&token=868bdaa0-1eca-481f-ac5a-b9a703866b3c", babyText: "Hello, is anyone there? Your baby’s heart starts to beat approximately 100 beats per minute at this stage, which is evident through a vaginal ultrasound. The fetal pole is the first visible sign of a developing embryo that has a curve from the head to the end which looks like a tail. Even though your baby is ½ an inch in length now, he/she won’t stay this way for long. Human features are starting to develop like the eyes and ears. The lungs and digestive system are also starting to branch out, forming the organs that will help your baby breathe and eat in just a few months.", bodyText: "You may be experiencing morning sickness (not just in the morning) you’ll also find that you’re more tired than before. Your body is adjusting to hormonal changes that are taking place which result in the feelings you are now having. It’s a delicate time in your pregnancy so be careful."),
      PregnancyBBInfo(week: 7, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_7.mp4?alt=media&token=ec4b94ce-dac9-4938-be1d-2a71f5efc318", babyText: "Your baby is still an embryo but is now forming all the important organs. The umbilical cord is now attached through which oxygen and food reaches your baby. Did you know that your body removes the baby’s waste through the umbilical cord? The arms that were forming now had hands forming looking like paddles at this point. Your little one now has more defined facial features compared to last week.", bodyText: "By now your uterus has increased in size and also your breasts.  You may feel cravings for certain kinds of foods which is totally normal.  Try however to eat healthy foods as what you eat is what you’re feeding your baby and you want him/her to develop properly. Heartburn alert! Try to avoid foods that trigger heartburn as you may experience it at this time."),
      PregnancyBBInfo(week: 8, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_8.mp4?alt=media&token=4bcfa286-d8a6-4fb7-a520-b33ee00fd106", babyText: "At 8 weeks your baby’s body is becoming straighter.  At this point, eyes, ears, nose and mouth are looking more obvious than last week. Your baby is growing really quickly even though you may not be showing as yet. The little toes and fingers are now starting to form and little buds that will become the genitals are starting to appear.", bodyText: "“Attention: you are now 2 months pregnant! If you have not seen your doctor as yet you should do so now.” So, you continue with the morning sickness and tiresome feelings?  Don’t be disheartened try incorporating a little ginger for the nausea, ginger crackers or ginger ale, some women opt for saltine biscuits but try whichever one works for you. Don’t be shy to ask for help from your partner or family members, support during pregnancy is important. You may find your clothes coming a little bit tighter around the waist, hey what gives? Because your baby is developing rapidly, the uterus has to expand in order to accommodate him/her."),
      PregnancyBBInfo(week: 9, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_9.mp4?alt=media&token=19f87eab-cdbc-46c7-8b69-d05f5458f748", babyText: "Heavyweight champion? Your baby is now developing muscles and may be making some moves in there.  You won’t be able to feel anything just yet as the embryo is nearly an inch long, though you might just see them if you had an ultrasound. Your baby’s head is growing quite larger than the rest of the body and the tail at the base of the spinal is almost gone. The digestive system continues to develop and the reproductive system starts to form.", bodyText: "It seems morning sickness and fatigue have become the new norm for you huh? Well this is because your body is working real hard preparing for your baby. To do so, your body reduces and increases some hormone levels that may seem to mess with you both internally and externally during these times.  Not to worry you will overcome.  After all you are taking part in the most important job in the world, making a baby!"),
      PregnancyBBInfo(week: 10, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_10.mp4?alt=media&token=73044751-520a-4614-a0b3-0e580d2fa75a", babyText: "Your baby by this time has passed the critical development stage as the vital organs are formed and is now ready to grow. Your baby is showing more distinct human features and the tail now is completely gone. If it’s a boy, well he’s developing testosterone around this point. Tooth buds are starting to form inside the mouth and those little fingers and toes are looking more defined.  “Houston, we have lift off”, baby’s brain is now functional.", bodyText: "Queasy feelings are in overdrive, swollen tender breasts, your clothes fit a little snugger than you remember; your body is working overtime preparing a placenta for your baby.  If you doubted you were pregnant before well for sure by now, you’re convinced. Off to the doctor’s office for your prenatal visit.  You may visit your Ob/Gyn or family doctor but whichever you choose they will be doing thorough examinations at this point, blood tests, pressure checks, blood sugar levels, internal and external examinations.  Be sure to talk to your doctor about any concerns and questions you may have. Also be open about your family medical history as these are important facts that will help during your pregnancy."),
      PregnancyBBInfo(week: 11, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_11.mp4?alt=media&token=322e9023-414c-4940-a669-4562bcbf9f43", babyText: "Although you are not able to feel it yet, your baby is more active assuming more positions. Remember Jimmy Neutron? Well your 2-inch long baby now looks more like him because the head accounts for most of that measurement. Not to worry, in the coming weeks you will find your little love bug’s body will become more proportionate in size. Even though it’s still early to tell the sex of the baby, it’s around this time that a girl starts to develop ovaries.", bodyText: "Feeling constipated? This is due to those hormones that cause your large intestines to move food slower than before. Drinking more water, and fiber from fruits, vegetables and whole grain can help here. Your expanding uterus is now the size of a grapefruit so you may be able to see a little bump at your lower abdomen, but nothing too striking. You may notice veins showing around your breast and tummy, not to worry, it’s all a part of the baby making a miracle."),
      PregnancyBBInfo(week: 12, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_12.mp4?alt=media&token=1db12228-ba19-4dc7-8960-672f0181c28f", babyText: "Your baby now looks like a fully formed person in the second to last week of the first trimester! Now the kidneys are up and running. Weighing half an ounce, your baby is now about the size of a lime and the toenails and fingernails are beginning to form.", bodyText: "By this time, you’ve gained 2 to 5 pounds, now you’re looking a little rounder and plumper. Your baby bump may or may not be showing depending on your body type and the number of pregnancies you’ve had. Just remember that every woman is different and reacts to hormonal changes differently."),
      PregnancyBBInfo(week: 13, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_13.mp4?alt=media&token=2420983b-695e-47f8-bb71-3125f03aa6cb", babyText: "At week 13 your baby’s eyelids are closed as the eye continues to develop.  By this time junior is now the size of a lemon and his vocal cords are starting to form.  The intestines that were growing close to the umbilical cord are now settled in the abdomen while it further develops. His little bones are forming and as his body grows, it is becoming more proportional in size. ", bodyText: "Your morning sickness and other pregnancy symptoms should be less this week as you close out the first trimester. However, since every woman is different, some symptoms may play out or subside throughout the pregnancy. You may notice an increased vaginal discharge (leukorrhea) which is caused by an excess of estrogen and blood flow to the pelvic area. You should be putting on some weight as your baby grows rapidly."),
      PregnancyBBInfo(week: 14, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_14.mp4?alt=media&token=d5f6e8f8-f084-4897-9d68-a5e2720b2670", babyText: "Your baby is now able to make facial expressions and has some tiny hairs called lanugo that covers the body. Don’t worry this will disappear before or after your baby is delivered.  Now an individual, your baby has developed fingerprints and is no longer slouching and is much straighter than before. Though constantly moving around you will not be able to feel it until later on.", bodyText: "You are doing well, you are now in the second trimester, which means you’re at month 4. Those around you who were suspecting may now see the truth as your baby bump becomes a little bit more noticeable. That is if they didn’t count that gorgeous glow you have looking nice and plump, your uterus is finally rising out of the pelvic region and into your lower abdomen. What is really cool is that you might even be able to feel the top of your uterus, called the fundus, if you press down right above your pelvic bone in your lower abdomen. Continue to eat and stay healthy."),
      PregnancyBBInfo(week: 15, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_15.mp4?alt=media&token=436c6593-5ed6-4c5f-a70d-87bf197e13e6", babyText: "As your baby’s skin continues to develop it is so thin that the blood vessels can be seen through it. Hair growth continues on the eyebrows and the head. As the skeletal and muscular system matures, your baby is now practicing some slick moves, flexing those little toes and making fists, kicking and moving around. You know that sucking motion and constant mouth moving that newborns seldom do; well your baby is starting now to get the knack of it.", bodyText: "Even though you may not be experiencing some symptoms like you did before, you may want to take note of your mouth. Your gums may become swollen and red sometimes bleed when you brush or floss. Stuffy? Some women experience stuffiness during this week and some even experience nose bleed. Seems to be forgetting stuff recently? Who is to blame? You guessed it, hormones. Yes, hormones are the ones messing with you during this time.   But not to worry it won’t last always after your body is through making your baby, things should go back to normal. What to do then you ask? Look after yourself, practice good oral hygiene along with eating and being healthy, talk to your doctor about exercising."),
      PregnancyBBInfo(week: 16, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_16.mp4?alt=media&token=721361e9-89ce-40d3-84fa-61275e2dee81", babyText: "Squinting and frowning have become a part of your baby’s routine as the facial muscles develop. Talking to your tummy? The bones in the ear have taken their place so your baby is now likely to hear your voice. Neat right? Your baby is now about the size of an avocado and is now all of 3-4 ounces and 4-5 inches long.", bodyText: "Your uterus is growing as fast as your baby is, you really need to start getting some maternity clothes. As every woman is different, every pregnancy is different, some women may still not show at this point while others do. Whichever side you’re on, don’t be hard on yourself, you are simply unique. You may find that your breasts are increasing in size as you gain weight to accommodate your baby. Remember to eat healthy only nutrient rich foods for you and your little one and the weight you gain would not be too overwhelming."),
      PregnancyBBInfo(week: 17, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_17.mp4?alt=media&token=9f343ab0-001b-4355-870d-7c583ad240e1", babyText: "At 17 weeks your baby’s skeleton is now bone as it changed from being a soft cartilage.   The placenta is growing steadily as it provides your little one with nutrients and oxygen and also removes wastes. The lungs are operational so is the circulatory system, your baby is growing well.", bodyText: "You may experience some aches and pain as your body changes to accommodate your baby; after all he is growing quite rapidly. You will find that your appetite has increased as you are eating for two. Ensure you are taking those vitamins your doctor prescribed and making healthier food choices.  Avoid alcohol at all cost and skip the junk food, you will thank me later. Remember to exercise but do so moderately, talk to your Ob/gyn about choosing the right kinds of exercises for your specific needs."),
      PregnancyBBInfo(week: 18, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_18.mp4?alt=media&token=7bcd8d9b-025d-4632-b5c2-6084af2d2408", babyText: "At 5 months your baby is about 5 ½ inches long and weighs around 5-6 ½ ounces. You may be able to feel little kicks and flutters as your growing baby moves around inside! The ears are now developed enough to hear you, your heartbeat and other sounds. Want to know the sex of your baby? The genitals are developed enough for an ultrasound to tell whether it’s a boy or girl.", bodyText: "You are definitely showing and may find people curiously staring, asking how far along you are or even ask if they could touch your tummy, even strangers; yikes! Let them know clearly whether you are comfortable or not with that. Stretch marks may be noticeable now, using moisturizing lotion can help. Leg cramps waking you up at night? Try doing some calf stretches before going to bed. Your swollen ankles are a result of fluid retention, try to elevate a little when you sit.  Back pain is common as your center of gravity is shifted but talk to your doctor about the best way to ease the pain."),
      PregnancyBBInfo(week: 19, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_19.mp4?alt=media&token=57cd33ff-6a2b-4c6d-b6f0-9674d8418ce6", babyText: "Now your baby's sensitive skin is covered with a greasy, white, cheese-like coating called vernix caseosa, that protects the skin from being wrinkled at birth. Did someone say baby fat? Your baby has now started to develop a thin layer of fat that will help her little body warm after birth.", bodyText: "As your baby’s hair grows, you may notice your hair thickening. This is triggered by… anyone? If you said hormones, then you are right! You may be wondering if sex during pregnancy is a good idea. As long as your pregnancy isn’t high risk and you are ok with it, you can.  But if you have any concerns be sure to talk to your doctor about it."),
      PregnancyBBInfo(week: 20, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_20.mp4?alt=media&token=07154199-ce5d-4a64-bf10-5db505438c63", babyText: "At the halfway mark, your baby weighs about 10 ounces and is 6 ½ inches in length. Your baby is now yawning and swallowing more. If it’s a boy his testicles are beginning their drop as it waits for the scrotum to finish developing.  If it’s a girl her uterus is fully formed and the development of the vaginal canal is also starting.", bodyText: "Now that you are mid pregnancy your baby is growing double time and so is your uterus as it accommodates your baby. You may notice your hair and nails growing faster and thicker but this is only for the duration of the pregnancy due to hormones. Even though you have those cravings and intensified appetite, don’t overdo it, moderation is key."),
      PregnancyBBInfo(week: 21, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_21.mp4?alt=media&token=6b943b95-bf6d-4bcf-9c23-76026c50d04c", babyText: "All systems are working in unison as your baby grows and matures. Your baby now has eyebrows, pretty cool huh? Little baby is also able to make more coordinated moves as the arms and legs are more proportional. The bone marrow is producing more red blood cells that will give oxygen to the baby's body.", bodyText: "You’ll be noticing stretch marks around your breast, stomach, thighs and butt area. I know, it can’t be avoided but moisturizing helps to soothe the skin if there is itching and dryness. If they haven’t started yet, your friends, co workers or others will be trying to touch your tummy and asking you how far along you are. And you definitely will be feeling more movements from your baby."),
      PregnancyBBInfo(week: 22, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_22.mp4?alt=media&token=310e81a9-67cd-4254-8dd0-5d6064f3d49f", babyText: "As your baby is growing, the body is doing some fine tuning.  Your baby now has taste buds forming on the tongue and his little brain and nervous system are correlating so he can feel. Baby boy or girl is this week weighing 1 pound and is now about 11 inches long from head to toe.", bodyText: "You may be feeling a squeezing sensation in your abdomen, it is your uterus practicing for delivery with painless contractions called Braxton Hicks contractions.  Don’t be worried about it. It's totally normal it won’t hurt you or your baby, it’s your body making preparation for the big day. However, if you experience any pain or prolonged discomfort please contact your doctor as soon as possible."),
      PregnancyBBInfo(week: 23, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_23.mp4?alt=media&token=4a090aa7-844f-4b3c-8d01-d2a19c081751", babyText: "Your baby is a little more than a pound this week and would be able to survive the outside world if premature labor occurs but may develop disabilities.  His skin is looking quite saggy or wrinkly at this point but he will fill out quite nicely soon. His little brain is making all the necessary connections that are needed for him to think.  Your baby is practicing breathing and he’s working out his muscles quite regularly.", bodyText: "Your doctor may encourage you to sleep on your sides and not on your back or stomach.  You may find it a little hard to get used to doing that but it is important to do so or you may end up causing a restriction of blood flow to the placenta.  You can use a pillow in between your legs to help with the pressure while you sleep. You may be finding yourself feeling anxious about what will happen later delivery and after.  It is good to have emotional support during your pregnancy from your family, friends or significant other."),
      PregnancyBBInfo(week: 24, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_24.mp4?alt=media&token=2aae82ea-393e-49ab-9fa1-f4d1660b9470", babyText: "This week your baby is putting on weight, more fat is developing making the once saggy or wrinkly skin tighter. As your baby’s hearing advances being able to recognize sounds is now possible. Baby’s sense of balance is also intact and is able to tell if he is upside down or not. Remember to get a nail clip for your baby, his fingernails are now present.", bodyText: "As your uterus grows, your once shy navel may be now more noticeable but this will go back to normal after birth.  You may be noticing that your shoes no longer fit properly as your ankles get swollen.  Try wearing more comfortable shoes that won’t cause your feet to hurt, you may want to avoid wearing those stilettos that you have in the closet.  Between 24 and 28 weeks your doctor will screen your blood glucose level that will indicate whether or not you have gestational diabetes that will have to be treated before it can cause harm to you or your baby."),
      PregnancyBBInfo(week: 25, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_25.mp4?alt=media&token=c3968497-58c6-4edd-a856-f77ecdcbeb29", babyText: "Baby’s heartbeat is now clearer, if your partner or previous child should hold their ear against your tummy, they are sure to hear a heartbeat! Your baby is more alert at this time and can clearly hear your voice, so be careful what you say ☺. That cute little button nose on his face is starting to work as your baby practices breathing. He’s actually breathing in amniotic fluid but this is not harmful. The sense of smell may kick in this week as well but as everyone is different it may happen in later weeks.", bodyText: "At 25 weeks you are now in your 6th month of pregnancy. Pretty hard not to notice that soccer ball you have for a tummy. Some pregnancy symptoms like heartburn and leg cramps may go on through to delivery.  Stay away from spicy foods or foods that trigger this symptom. Do what works for you and what your body reacts best to. It’s a good time to start thinking of baby names if you haven’t started yet. Remember to choose carefully and be mindful of what the name means."),
      PregnancyBBInfo(week: 26, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_26.mp4?alt=media&token=1aab34e3-f19d-4343-885e-757b54d12eb0", babyText: "Your baby is now all of 2 pounds and 14 inches long with eyes that are wide open. Eyelashes and eyebrows are grown in and on his wee little head. Your baby is really growing and is starting to fill out the uterus. He or she may not have enough space for somersaults or cartwheels but will continue to move as is possible.  Your baby’s brain is getting so advanced that he can not only hear sounds but be able to respond to them, how neat?", bodyText: "As your baby gets bigger you may feel like you have a martial arts expert in your womb. Yep those kicks and punches are more pronounced mainly because your baby is well bigger and is taking up more space - hence there is less room for him to practice his moves. You might be having trouble sleeping along with all those other symptoms that have stayed with you.  Don’t freak out about it to make matters worse, talk to your doctor about what you can do to safely help with insomnia. Remember to eat healthy and to take care of yourself, remove or limit stress factors. Try doing exercises which are approved by your doctor that will keep you healthy and stress free. Do Kegel exercises (which your doctor might have mentioned) that will help during delivery."),
      PregnancyBBInfo(week: 27, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_27.mp4?alt=media&token=23e9cafe-66dc-4b90-85fa-a1a65a3507c6", babyText: "In the last week of the second trimester, your baby is more active and is developing fast.  All the organs are maturing and working well, but still have a bit of fine tuning to do. You’ll notice your baby has developed a schedule when sleeping and when awake which oftentimes is very different from yours.  Even though your voices may be muffled because of a vernix, a thick wax that covers the skin, your baby can tell mommy’s voice is different from daddy’s. The nerve and brain are working sending and receiving signals to all parts of the body. Baby may have a hiccup at times.", bodyText: "As your baby puts on weight, so do you. You might have heard from your friends or others that you are totally rocking those maternity clothes ;) Don’t worry the pounds you put on now will go after the birth of your baby even though you’ll have to work it off. Finding yourself opting for more comfy shoes lately? Having trouble putting on or taking off your ring? This is quite normal during pregnancy but if you have any concerns or questions do not hesitate to share with your doctor."),
      PregnancyBBInfo(week: 28, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_28.mp4?alt=media&token=00b8023c-4c30-4120-8fbf-bd1a66bb920e", babyText: "At 28 weeks you’ve entered the 7th month of pregnancy only 2 more months to go! In addition to packing on the pounds, your baby is finding himself in the childbirth position, getting ready for the big day.   If your baby isn’t in the birth position don’t panic there is still a little time in which this can happen. You’ll find it interesting to know that your little one is dreaming, maybe of finally seeing your face. Speaking of the face, your baby may be making some faces of his own, smiling, sticking the tongue out and frowning.", bodyText: "In your third trimester, your doctor’s appointments may be more frequent from now on as premature labor at this stage is possible.  Don’t be scared though it may not happen to you but just to be safe it's time to start packing your bag for you and your baby that you will take to the hospital. You may already know the sex of your baby if you chose to so you’ll know exactly what color scheme and gender your working with. As your baby makes preparation for entering the world, you should make your preparations for his arrival."),
      PregnancyBBInfo(week: 29, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_29.mp4?alt=media&token=3c1f47c3-ef3d-4640-a47f-4c563f83f49d", babyText: "Continuing to grow, your baby is about 2 ½ to 3 pounds in weight and is 15 ½ to 16 inches long. At this size it can get cramped inside your tummy, so those little flutters you were used to will be more like strong right cross, uppercuts, elbows and knee kicks now. It’s important to monitor the movement of your baby (start counting those kicks) so you can know if he/she is alright. If your baby is not moving as he should, then you must talk to your Ob/Gyn as soon as possible. ", bodyText: "By now it may be hard for you to see your toes when you’re standing up. The bigger you get, the more stretched your skin becomes so moisturizing can help with the itching that comes with that. Along with swollen ankles you may notice varicose veins on your feet as well, some women find them painful others don’t.  If you do, talk to your doctor, remember you are not in this alone. As you count kicks lie on your back and count every movement you feel.  If you count less than 10 in an hour, have a little snack and check again; your baby will get an extra kick from the sugar.  Contact your doctor immediately if your baby is not responsive."),
      PregnancyBBInfo(week: 30, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_30.mp4?alt=media&token=e267ba52-7814-418b-a150-075404b014a9", babyText: "Your little nugget is adding on layers of fat that will keep him warm as the lanugo (little fur like covering on the skin) becomes less.  Looking as big as a bunch of broccolis, your baby is almost weighing 3 pounds. It’s interesting to note that the baby's brain is developing convolutions (those wrinkles on the brain) so that it can hold more brain cells.", bodyText: "Other than the baby’s movement you may be feeling some strange feeling in your body.  This is because your joints are loosening as your body prepares itself for delivery.  Heartburn and fatigue have now crept back into the picture. Your breasts which have gone up a cup size or two are a little tender as your body prepares the production of milk for your baby. Because of your expanding uterus putting pressure on your bowels you may become constipated."),
      PregnancyBBInfo(week: 31, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_31.mp4?alt=media&token=ecb310af-3385-4a68-b297-f6f87067e22e", babyText: "Putting on the finishing touches your baby’s brain is making integral connections so that the five senses are operational. The lungs are in the final stages of development however if your baby meets you this week, he’ll be able to breathe with the help of a ventilator. Now taking longer naps, your baby has a steadier schedule for the day so you’ll recognize when he’s awake or sleeping.", bodyText: "Your growing uterus is pushing everything on the inside of your body out of its position like your lungs.  No wonder you’re having shortness of breath! Your lungs are unable to expand as it normally would to take in as much air as it did before.  Now you know what’s going on, don’t get too worried this shortness of breath will pass as your baby drops lower to your pelvis for him to make his way out. Up until now you may be okay with sex, don’t worry you can still enjoy your partner but in positions that are pregnancy friendly.  Your baby won’t be harmed but if you have concerns talk to your partner about it and your doctor so you can remove the worry."),
      PregnancyBBInfo(week: 32, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_32.mp4?alt=media&token=46035a18-af04-4bcd-bbc4-637b06bcfbe1", babyText: "At 32 weeks or 8 months, your baby now has fully formed organs, well except for the lungs. If your baby were to be born now your little trooper would be able to survive on his own. He’s now 3 ½ to 4 pounds in weight and 15 to 17 inches long, wow he’s the size of a cantaloupe. Even though there is far less room inside for your baby to be doing much movement he is still comfortable.", bodyText: "This week your body will be making its preparation delivery, you will be experiencing more Braxton Hicks contractions.  This is a tightening that you feel in the uterus which is basically flexing. If you find it going on for more than 2 minutes and don’t stop when you change position, call your doctor right away to ensure you have not gone into labor. Your Ob/Gyn will at your next visit monitor your blood pressure level and check for anything that is out of the ordinary, so keep those appointments."),
      PregnancyBBInfo(week: 33, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_33.mp4?alt=media&token=cc60ff6b-123e-43dd-abe2-bee22accae11", babyText: "In the final weeks to deliver your baby will be putting on about a half a pound a week. The little bones are getting stronger and are hardened with exception of the skull.  The skull is still soft so your baby can come through the birth canal head first.  The senses are kicking and he’s now able to differentiate day time from night time and closing his eyes when asleep and opening them when awake.  Your baby is gearing up for his arrival to the world, he now has his own immune system.", bodyText: "As you count down the weeks to delivery you may want to sign up for a Lamaze class if you haven’t as yet if you are interested. Thinking of the upcoming events, wondering how you’re going to deal with the pain? Talk to your doctor about options you can take during delivery, whether you opt for an epidural or not, try to prepare yourself mentally for what might happen.  Don’t worry about it, that will only make things worse, just try to be prepared or have an open mind."),
      PregnancyBBInfo(week: 34, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_34.mp4?alt=media&token=e81e2ab4-6e53-4b88-80d7-1a4f1860e76d", babyText: "Your baby now weighs about 5 pounds right now and is about 18 inches long.  He should be in the head down position by now (but he still has a little more time to do that) if not your doctor may talk to you about doing a cesarean cut to remove your baby. So, it’s pretty congested in the uterus now, don’t be surprised if you notice your baby’s knee or elbow poking through your belly! And he’s still growing and fine tuning.", bodyText: "You might find yourself being tired and having trouble sleeping at night. Aches and pain here and there along with the extra pounds you have moving around with is no fun. Don’t be disheartened, you are on the second to last stretch.  You need to rest as much as possible right now because when your bundle of joy comes you will be in it for the long haul.  So, take time for yourself, try to relax and treat yourself while staying healthy."),
      PregnancyBBInfo(week: 35, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_35.mp4?alt=media&token=c8eb9e73-07f1-4618-91a7-f327de11c2bc", babyText: "Your baby is packing on the fat as he becomes plumper by the week. That loose and wrinkly skin that once was, is looking chubbier and chubbier.  You will be feeling his movements but not as much since the room is practically full. The closer you get to your delivery date the further done the pelvic area your baby goes, getting ready for THE day.", bodyText: "As your baby goes further down the pelvic area your lungs will be breathing a sigh of relief.  Your bladder on the other hand, not so much as you will be making frequent trips to the bathroom. “Hello is anyone there?” Your baby is in a tight spot right now so if you don’t feel drastic moves as before that would be why.  If you find that your baby is far too quiet, talk to your doctor and share your concerns."),
      PregnancyBBInfo(week: 36, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_36.mp4?alt=media&token=a92261ba-96e2-46d9-8dcb-9b27dbbaafa2", babyText: "Your baby is growing and maturing very nicely as you are now in your 9th month of pregnancy.  He is now about 6 pounds in weight and about 18 to 19 inches long. The growth process will slow down over the coming weeks so that your baby will have the energy needed for delivery and so he can fit through the birth canal! Most of your baby’s organs and systems are up and ready but the digestive system is not yet completed and may take some time after birth to be.", bodyText: "Along with your aching back and frequent trips to the bathroom you may be full of anxiety. Try to remain calm and not to stress out too much about what is to come.  You want to be informed and aware but don’t work yourself into complications that will only make things worse.  Continue eating healthy, getting plenty of rest and doing some light exercises like walking may come in handy when it comes time to push. You will be seeing your doctor more often now, once every week as necessary, remember we want everything to go smoothly for the big day."),
      PregnancyBBInfo(week: 37, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_37.mp4?alt=media&token=ffca0216-f160-41a0-971a-ac1067d06223", babyText: "At 37 weeks your bundle of joy is 6 ½ pounds and is doing final practices for his arrival any time soon!  He is practicing breathing in and exhaling amniotic fluid and working those jaws with sucking motions- probably sucking his thumb. As he fills out, your little prince or princess is flexing those muscles and coordinating, he or she is able to grab on to things he/she may be grabbing those little toes right now.  Baby’s immune system is prepping and ready to go as he descends lower into the pelvis. Be ready he may be making his appearance any time soon.", bodyText: "Your doctor will be monitoring you weekly for new developments and signs as the pregnancy progresses.  You may notice an increase in vaginal discharge as you move further.  You may feel as if your lower back is stretching, also your cervix may be moving more towards the front of your body, this is in preparation for your baby’s arrival. The cervix has to dilate 10 cm for your baby to pass through into the birth canal. As the cervix dilates or expands the mucus plug that once sealed your uterus to prevent infections will be discharged from your body. You may notice a “bloody show” which is a pink or brown discharge from the mucus plug or ruptured blood vessels in the cervix.   Ensure to talk to your doctor about any change you may notice."),
      PregnancyBBInfo(week: 38, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_38.mp4?alt=media&token=d66bbdc2-52bc-4b69-a36d-52e444ec30de", babyText: "Gaining another half-pound, your baby now weighs 7 pounds and is now 20 inches long. He’s now behaving like a newborn, having sleep and feeding patterns. “Sound the alarm!” Baby’s lungs are stronger now and his little vocal cords are ready to work, get ready for his resounding cries. As your baby preps for birth, the final touches are still on the way. Over the past few months, he has been swallowing amniotic fluid and other waste has accumulated in the intestines.  After birth, this will be your baby’s first bowel movement called meconium.", bodyText: "As you move closer to your due date you will experience some amount of anxiety and sleepless nights. As your body is doing its preparation you may find yourself to be one of the many women that notice fluid leaking from the nipples.  This fluid is called colostrum, a yellowish substance that comes before the actual milk is loaded with antibodies and protein that is easy for the baby to digest. If you haven’t noticed this, don’t worry as you may be one who has that after the birth of your baby."),
      PregnancyBBInfo(week: 39, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_39.mp4?alt=media&token=7e8e4f72-ef58-4ce1-9ccf-e9f02a31e4e4", babyText: "Your baby is now between 7-9 pounds and measures 19-21 inches. All that he needs to survive independent of the placenta is downloaded.  His once pink skin is now turned white, his complexion will change as pigmentation will occur some time after birth. Even though he’s not growing much now, his brain is still growing quite quickly and will continue for the first 3 years after birth.", bodyText: "You may find yourself being more restless, anxious and uncomfortable as your baby bears down on your pelvis. While you wait for his arrival, if you haven’t already packed your bag ensure that you have all that you will need if you have to make a quick trip to the hospital. As labor is right around the corner, Braxton Hicks contractions may be intensifying and are more frequent. You’ll be now looking out for signs which indicate that you’re in labor. Your water may break, the mucus plug discharge and bloody show are all indicators of the onset of labor.  If you are experiencing any or all of these, talk to your doctor, it may be time to get going."),
      PregnancyBBInfo(week: 40, videoUrl: "https://firebasestorage.googleapis.com/v0/b/coraltrackerapp.appspot.com/o/pregnancy-videos-files%2FWeek_40.mp4?alt=media&token=91e3e6d4-8db6-4f46-b35d-19befa1878ae", babyText: "Congratulations, you have reached the final stage of your pregnancy!  If you haven’t gotten to meet your handsome prince or beautiful princess as yet, your placenta is still providing him/her with antibodies to fight off infections for the first 6 months after birth. Remember the due date is an estimated date, your baby may come on, before or after that date. Since the vernix (the waxy coat that moisturized your baby’s skin) has shed, your baby’s skin may be dry or has little dry patches.", bodyText: "There are some pregnancies that go past the 40-week mark, maybe you’re in that number. Talk to your doctor and share your concerns or fears.  If your body hasn’t naturally gone into labor, it may have to be induced.  If there are no issues with your pregnancy, an ultrasound may indicate that your baby may be too comfortable in your uterus and is not ready to come out. It may also show that there may be some complications which may require you to have a C-section.  So, talk to your doctor."),
    ];
  }

}